name: Update Arduino libs

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC = 08:00 Asia/Almaty
  workflow_dispatch:
    inputs:
      run_arduino_esp32:
        type: boolean
        default: true
        description: "Обновлять arduino-esp32?"
      run_radiolib:
        type: boolean
        default: true
        description: "Обновлять RadioLib (пин 6.5.0)?"
      run_mbedtls:
        type: boolean
        default: true
        description: "Обновлять mbedTLS?"

concurrency:
  group: update-libs
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-libs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --- Arduino core for ESP32 (последняя дефолтная ветка) ---
      - name: Fetch Arduino core for ESP32
        if: ${{ github.event_name == 'schedule' || inputs.run_arduino_esp32 == true }}
        run: |
          set -e
          rm -rf libs/arduino-esp32
          git clone --depth 1 https://github.com/espressif/arduino-esp32.git libs/arduino-esp32

      # --- RadioLib: жёстко пин на теге 6.5.0 (без префикса v) ---
      - name: Fetch RadioLib 6.5.0
        if: ${{ github.event_name == 'schedule' || inputs.run_radiolib == true }}
        run: |
          set -e
          rm -rf libs/RadioLib
          # Клонируем сразу по тегу: это устраняет ошибку с отсутствующим тегом в shallow-истории
          git clone --depth 1 --branch 6.5.0 https://github.com/jgromes/RadioLib.git libs/RadioLib
          cd libs/RadioLib
          # Верифицируем, что HEAD именно на теге 6.5.0
          git describe --tags --exact-match

      # --- mbedTLS (последняя дефолтная ветка) ---
      - name: Fetch mbedTLS
        if: ${{ github.event_name == 'schedule' || inputs.run_mbedtls == true }}
        run: |
          set -e
          rm -rf libs/mbedtls
          git clone --depth 1 https://github.com/Mbed-TLS/mbedtls.git libs/mbedtls

      # --- Создаём/обновляем один и тот же PR с изменениями ---
      - name: Create/Update PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-libs
          title: "chore: update Arduino libs"
          commit-message: "chore: update Arduino libs [skip ci]"
          body: |
            Automated library refresh.

            - arduino-esp32: latest default branch (shallow)
            - RadioLib: **pinned to 6.5.0**
            - mbedTLS: latest default branch (shallow)
          labels: |
            dependencies
            automated-pr
